services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: vennai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
