"""point Question FK to survey_version_id

Revision ID: 00a0bd67a45d
Revises: b184c587b6c3
Create Date: 2025-07-30 09:44:36.822284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00a0bd67a45d'
down_revision = 'b184c587b6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questions_survey_id_fkey'), type_='foreignkey')
        batch_op.drop_column('survey_id')

    with op.batch_alter_table('survey_versions', schema=None) as batch_op:
        batch_op.alter_column('imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_survey_active_per_slug'), postgresql_where='is_active')
        batch_op.create_index('uq_active_version_per_survey', ['survey_id'], unique=True, postgresql_where=sa.text('is_active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_active_version_per_survey', postgresql_where=sa.text('is_active'))
        batch_op.create_index(batch_op.f('ix_survey_active_per_slug'), ['survey_id'], unique=True, postgresql_where='is_active')
        batch_op.alter_column('imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('questions_survey_id_fkey'), 'surveys', ['survey_id'], ['survey_id'])

    # ### end Alembic commands ###
