"""add survey versioning

Revision ID: 00f75907cf2f
Revises: b309f41a6da7
Create Date: 2025-07-30 03:35:56.898302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer


# revision identifiers, used by Alembic.
revision = '00f75907cf2f'
down_revision = 'b309f41a6da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("surveys", sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column("surveys", sa.Column('schema_hash', sa.String(length=64), nullable=True))
    op.add_column("surveys", sa.Column('revision', sa.Integer(), nullable=True))

    surveys = table("surveys", column("revision", Integer))
    op.execute(surveys.update().where(surveys.c.revision == None).values(revision=1))

    op.alter_column('surveys', 'revision', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_column('schema_hash')
        batch_op.drop_column('is_active')
        batch_op.drop_column('revision')

    # ### end Alembic commands ###
