"""updated answer table

Revision ID: 2620caab9814
Revises: 31f00e4538fa
Create Date: 2025-07-20 18:41:05.014106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2620caab9814'
down_revision = '31f00e4538fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.UUID(), nullable=False))
        batch_op.alter_column('free_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['question_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('free_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
