"""added analysis column to response

Revision ID: 5d7b598a4ff7
Revises: c3aaa00ee461
Create Date: 2025-07-24 23:29:56.996969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7b598a4ff7'
down_revision = 'c3aaa00ee461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.JSON(), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###
