"""Add instructions to option_sets

Revision ID: 8e7962af93fb
Revises: fbb22a908acd
Create Date: 2025-07-23 04:48:59.846228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7962af93fb'
down_revision = 'fbb22a908acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_sets', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
