"""added table_args to revision

Revision ID: af32414d02aa
Revises: 00f75907cf2f
Create Date: 2025-07-30 04:12:59.399524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af32414d02aa'
down_revision = '00f75907cf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index('ix_survey_active_per_slug', ['typeform_id'], unique=True, postgresql_where=sa.text('is_active'))
        batch_op.create_unique_constraint(None, ['typeform_id', 'revision'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_survey_active_per_slug', postgresql_where=sa.text('is_active'))

    # ### end Alembic commands ###
