"""add typeform_id to survey

Revision ID: b309f41a6da7
Revises: 54e29131cc79
Create Date: 2025-07-30 02:45:49.351843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b309f41a6da7'
down_revision = '54e29131cc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typeform_id', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_surveys_typeform_id'), ['typeform_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_typeform_id'))
        batch_op.drop_column('typeform_id')

    # ### end Alembic commands ###
