"""added typeform ref to questions and options

Revision ID: ba899bd92a9f
Revises: 494df1f74217
Create Date: 2025-08-03 06:44:17.498041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba899bd92a9f'
down_revision = '494df1f74217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typeform_ref', sa.String(length=128), nullable=True))
        batch_op.create_index("ix_options_typeform_ref", ['typeform_ref'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typeform_ref', sa.String(length=128), nullable=True))
        batch_op.create_index("ix_questions_typeform_ref", ['typeform_ref'], unique=False)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('survey_version_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('survey_version_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index("ix_questions_typeform_ref")
        batch_op.drop_column('typeform_ref')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index("ix_options_typeform_ref")
        batch_op.drop_column('typeform_ref')

    # ### end Alembic commands ###
