"""make options.question_id nullable

Revision ID: c3aaa00ee461
Revises: 8e7962af93fb
Create Date: 2025-07-23 06:02:18.080599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aaa00ee461'
down_revision = '8e7962af93fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
